# Generated by Django 5.1.1 on 2024-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0004_rename_created_at_surveyresponse_submitted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='payment_procedures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
