# Generated by Django 5.1.1 on 2024-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0006_gymrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymrule',
            name='file',
            field=models.FileField(default=1, upload_to='gym_rules/'),
            preserve_default=False,
        ),
    ]
