# Generated by Django 5.1.1 on 2024-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0007_gymrule_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='gym_notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
