# Generated by Django 5.1.1 on 2024-09-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0015_remove_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GymSlot',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
