# Generated by Django 4.2.11 on 2024-10-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0016_remove_booking_slot_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymnotice',
            name='file',
        ),
    ]
