# Generated by Django 5.1.1 on 2024-10-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0021_gymslot_booked_by_gymslot_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='plan',
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
