# Generated by Django 5.1.1 on 2024-10-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0022_remove_membershipplan_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='plan',
            field=models.CharField(default='Basic Plan', max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
